// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrwhuitkkelerbhtpqpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyd2h1aXRra2VsZXJiaHRwcXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDM4MjMsImV4cCI6MjA2Mzg3OTgyM30.-2gPyItNhHXqceT2ifxeuvdDBCLkh_mwDHTxpplhTWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);